# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zobCfI0J9OAEoUe-s2AB58sOxbt82l4
"""

title,text,subject,date,label
Donald Trump Sends Out Embarrassing New Year's Eve Message,Donald Trump just couldn’t wish all Americans a Happy New Year. No, he had to be a jerk...,politicsNews,December 31, 2017,FAKE
Watch The Exact Moment Paul Ryan Committed Political Suicide,Republican Speaker of the House Paul Ryan is facing a serious crisis in his party...,worldnews,December 30, 2017,FAKE
Trump’s Strategy on North Korea: ‘Maximum Pressure’ and Engagement,The Trump administration is planning to ramp up its sanctions...,politicsNews,January 1, 2018,REAL
New study reveals shocking truth about climate change,According to a new scientific study, climate change is progressing much faster...,environment,January 5, 2018,REAL
Breaking: Obama secretly met with foreign leaders during Trump presidency,An explosive report reveals that former President Obama was engaged in covert meetings...,politicsNews,January 2, 2018,FAKE